site_name: Tiere
dev_addr: '127.0.0.1:8001'

theme:
  name: material
  features:
    - toc.integrate
extra_css: [/Produktion/css/base.css]

markdown_extensions:
  - toc:
      title: "Inhalt"
      separator: "_"
      baselevel: 1
      permalink: false # default
  - attr_list

nav:
  - "Katzen": "content/Tiere/1_Katzen/Katzen.md"
  - "Hunde": "content/Tiere/2_Hunde/Hunde.md"
  - "Vogel": "content/Tiere/3_Vogel/Vogel.md"
  - "Fische": "content/Tiere/4_Fische/Fische.md"
