@startuml
|Schwimmbahn 1|
start
:Anweisung 1;
|#Antiquewhite|Schwimmbahn 2|
:Anweisung 2;
if(Bedingung 1) then (true)
|Schwimmbahn 1|
:Anweisung 3;
else (false)
|Schwimmbahn 3|
:Anweisung 4;
:Anweisung 5;
endif
|Schwimmbahn 2|
#palegreen:Anweisung 6;
:Anweisung 9;
repeat
|Schwimmbahn 3|
backward:Anweisung 7;
|Schwimmbahn 2|
repeat while (Bedingung 3) is (true) not (false)
|Schwimmbahn 1|
:Anweisung 8;
end
@enduml